src/java/com/mobinil/gvms/system/admin/beans/EditGiftType.java
package com.mobinil.gvms.system.admin.beans;


import com.mobinil.gvms.system.admin.giftType.DAO.GiftTypeDAO;
import com.mobinil.gvms.system.admin.giftType.DTO.GiftTypeDTO;
import com.mobinil.gvms.system.admin.login.loginDTO.LoginDTO;
import com.mobinil.gvms.system.utility.*;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.faces.component.html.HtmlCommandButton;
import javax.faces.component.html.HtmlForm;
import javax.faces.component.html.HtmlInputText;
import javax.faces.component.html.HtmlInputTextarea;
import javax.faces.component.html.HtmlOutputLabel;
import javax.faces.context.FacesContext;


public class EditGiftType
{
  public HtmlForm form1;  
  public String GiftTypeName;
  public String GiftTypeDescription;
  public Integer GiftTypeValue;
  public String status;
  Integer GiftTypeId;
  public HtmlInputText nameInputText;
  public String name;
  public String value;
  public String description;
  public HtmlCommandButton updateButton;
  public HtmlInputTextarea descriptionInputTextarea;
  public HtmlOutputLabel msgWarn;
  public HtmlCommandButton backToGiftType;

    GiftTypeDTO gtdto = null;
  public EditGiftType()
  {
        new leftMenu().checkUserInSession();
        gtdto = (GiftTypeDTO)jsfUtils.getFromSession("GiftTypeInfo");
        
    GiftTypeId = gtdto.getGiftTypeId();
        
    GiftTypeName = gtdto.getGiftTypeName();
        
    name = GiftTypeName;

    GiftTypeDescription = gtdto.getGiftTypeDescription();
        
    description = GiftTypeDescription;
    status = gtdto.getGiftTypeStatusId()+"";        
  }

  public String updateGiftType_Action()
  {
    // Add event code here...
	  if (description.length() > 1000)
      {
        msgWarn.setValue("Maximum characters for description are 1000.");

        return null;
      }   
	  GiftTypeName = nameInputText.getValue().toString().trim();
	  
    if (GiftTypeName==null || GiftTypeName.compareTo("") == 0 ||
         status.compareTo("0") == 0)
      {

        msgWarn.setValue("Please fill star boxes.");
        return null;
      }
    
    try
      {
          String dd= GiftTypeDAO.checkDublicatedGiftTypeName(nameInputText.getValue().toString().trim(),GiftTypeId);
        if (dd.compareTo("")!=0)
          {
            msgWarn.setValue("this gift type already exists.");
            return null;
          }
        else
          {
            
            String creatorName = 
              ((LoginDTO) jsfUtils.getFromSession("adminInfo")).getFullName();
            if (status.compareTo("0") != 0)
              {
                int update =
                  GiftTypeDAO.updateGiftType(GiftTypeName, status,creatorName,descriptionInputTextarea.getValue().toString(),GiftTypeId);
                  
                if (update == 0)
                  {
                    msgWarn.setValue("Gift type name is missing");
                    return null;
                  }
                else
                  {
                    msgWarn.setValue("Update Complete");
                    return null;
                  }
              }
            else
              {
                msgWarn.setValue("Please select status for " + name);
                return null;
              }
          }
      }
    catch (SQLException e)
      {
         new com.mobinil.gvms.system.utility.PrintException().printException(e);
      }

    return null;
  }

  public String getDateTime()
  {
    java.util.Date currentDate = new java.util.Date();
    int currentYear;
    currentYear = currentDate.getYear() + 1900;
    int currentMonth = currentDate.getMonth() + 1;
    int currentDay = currentDate.getDate();
    int currentHour = currentDate.getHours();
    int currentMin = currentDate.getMinutes();
    int currentsec = currentDate.getSeconds();
    String strCurrentDate = 
      currentMonth + "/" + currentDay + "/" + currentYear + " " + currentHour + ":" + currentMin + 
      ":" + currentsec;
    //System.out.println(strCurrentDate);
    return strCurrentDate;

  }

  public String convertDate(String values)
  {
    if (values == null)
      {
        ;
        String[] toDate = new String[3];
        toDate[0] = "00";
        toDate[1] = "00";
        toDate[2] = "0000";
        values = "to_date('" + toDate[0] + "/" + toDate[1] + "/" + toDate[2] + "', 'MM/DD/YYYY')";
        return values;
      }
    else
      {
        String[] toDate = values.split("/");

        values = 
            "to_date('" + toDate[0] + "/" + toDate[1] + "/" + toDate[2] + "', 'MM/DD/YYYY HH24:MI:SS')";
        //System.out.println(values);
        return values;
      }
  }

  public void setForm1(HtmlForm form1)
  {
    this.form1 = form1;
  }

  public HtmlForm getForm1()
  {
    return form1;
  }

  public void setGiftTypeName(String GiftTypeName)
  {
    this.GiftTypeName = GiftTypeName;
  }

  public String getGiftTypeName()
  {
    return GiftTypeName;
  }

  public void setGiftTypeDescription(String GiftTypeDescription)
  {
    this.GiftTypeDescription = GiftTypeDescription;
  }

  public String getGiftTypeDescription()
  {
    return GiftTypeDescription;
  }

  public void setGiftTypeValue(Integer GiftTypeValue)
  {
    this.GiftTypeValue = GiftTypeValue;
  }

  public Integer getGiftTypeValue()
  {
    return GiftTypeValue;
  }

  public void setNameInputText(HtmlInputText inputText1)
  {
    this.nameInputText = inputText1;
  }

  public HtmlInputText getNameInputText()
  {
    return nameInputText;
  }


  public void setUpdateButton(HtmlCommandButton commandButton1)
  {
    this.updateButton = commandButton1;
  }

  public HtmlCommandButton getUpdateButton()
  {
    return updateButton;
  }


  public void setDescriptionInputTextarea(HtmlInputTextarea inputTextarea1)
  {
    this.descriptionInputTextarea = inputTextarea1;
  }

  public HtmlInputTextarea getDescriptionInputTextarea()
  {
    return descriptionInputTextarea;
  }

  public void setMsgWarn(HtmlOutputLabel outputLabel1)
  {
    this.msgWarn = outputLabel1;
  }

  public HtmlOutputLabel getMsgWarn()
  {
    return msgWarn;
  }


  public void setName(String name)
  {
    this.name = name;
  }

  public String getName()
  {
    return name;
  }

  public void setValue(String value)
  {
    this.value = value;
  }

  public String getValue()
  {
    return value;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public String getDescription()
  {
    return description;
  }

  public void setBackToGiftType(HtmlCommandButton commandButton1)
  {
    this.backToGiftType = commandButton1;
  }

  public HtmlCommandButton getBackToGiftType()
  {
    return backToGiftType;
  }

  public String back_Action()
  {
    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().remove("GiftType_Bean");
    return "backtoGiftType";
  }

  public void setStatus(String status)
  {
    this.status = status;
  }

  public String getStatus()
  {
    return status;
  }
}

src/java/com/mobinil/gvms/system/admin/beans/GiftType.java
package com.mobinil.gvms.system.admin.beans;


import com.mobinil.gvms.system.admin.giftType.DAO.GiftTypeDAO;
import com.mobinil.gvms.system.admin.giftType.DTO.GiftTypeDTO;
import com.mobinil.gvms.system.utility.*;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import javax.faces.component.html.HtmlDataTable;
import javax.faces.component.html.HtmlForm;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import javax.servlet.http.HttpSession;


public class GiftType
{
  public ArrayList<GiftTypeDTO> GiftTypeArray = new ArrayList<GiftTypeDTO>();
  GiftTypeDTO dataItem;
  
  public HtmlForm form1;
  public HtmlDataTable dataTable1;
  public String msgWarn;
  public Integer rowCount = 10;
  int pageIndex = 0;

  public List<GiftTypeDTO> selectedDataList;
  public String sortField = null;
  public boolean sortAscending = true;

  public GiftType()
  {
      new leftMenu().checkUserInSession();
      
    
    try
      {
         GiftTypeArray =  GiftTypeDAO.getGiftTypeInfo();
        for (int k =0 ;k<GiftTypeArray.size() ; k++)          
          {
            
            GiftTypeDTO g = GiftTypeArray.get(k);
              int giftId = g.getGiftTypeId();
            

            try
              {
                Integer id = 
                  (Integer) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("rowNumber" + 
                                                                                                       giftId);
                //System.out.println("id is" + id);

                if (id == giftId)
                  {

                    g.setSelected(true);
                    msgWarn = "Delete operation failed due to active gifts.";
                  }
              }
            catch (Exception e)
              {
new com.mobinil.gvms.system.utility.PrintException().printException(e);
              }
            


          }

        
      }
    catch (Exception e)
      {
         new com.mobinil.gvms.system.utility.PrintException().printException(e);
      }

    for (int counter1 = 0; counter1 < GiftTypeArray.size(); counter1++)
      {
        Map sessionMap = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
        HttpSession session = 
          (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);

        String[] beanNames = session.getValueNames();
        for (int x = 0; x < beanNames.length; x++)
          {
            if (beanNames[x].contains("rowNumber"))
              {

                if (sessionMap.containsKey(beanNames[x]))
                  {
                    sessionMap.remove(beanNames[x]);
                  }

              }
          }

      }
  }

  public void sortDataTable(ActionEvent event)
  {
    String sortFieldAttribute = getAttribute(event, "sortField");

    // Get and set sort field and sort order.
    if (sortField != null && sortField.equals(sortFieldAttribute))
      {
        sortAscending = !sortAscending;
      }
    else
      {
        sortField = sortFieldAttribute;
        sortAscending = true;
      }

    // Sort results.
    if (sortField != null)
      {
        Collections.sort(GiftTypeArray, new DTOComparator(sortField, sortAscending));
      }


  }

  public static String getAttribute(ActionEvent event, String name)
  {
    return (String) event.getComponent().getAttributes().get(name);
  }

  public String getSelectedItems()
  {
    String gifts = "";
    // Get selected items.
    selectedDataList = new ArrayList<GiftTypeDTO>();
    int count = 1;

    for (int counter = (dataTable1.getRows() * pageIndex); counter < GiftTypeArray.size(); 
         counter++)


      {
        if (counter == (dataTable1.getRows() * (pageIndex + 1)))
          {
            break;
          }
        GiftTypeDTO dataItems = new GiftTypeDTO();
        dataItems = GiftTypeArray.get(counter);
        if (dataItems.getSelected())
          {
            selectedDataList.add(dataItems);
            dataItems.setSelected(false); // Reset.
            int id = dataItems.getGiftTypeId();
            String activeGifts="";
                  try {
                      activeGifts = GiftTypeDAO.getActiveGiftTypes(id);
                  
                if (activeGifts.compareTo("") == 0)
                  {
                    int delete = GiftTypeDAO.deleteGiftType(id);
                      
                    if (delete == 1)
                      {
                        UpdateClass.updateGiftTypeInfo(id+"", true);
                        msgWarn = "Gift type " + id + "deleted";
                      }
                    else
                      {
                        msgWarn = "Gift type not deleted";
                      }
                      
                  }
                else
                  {
                    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("rowNumber" + 
                                                                                               dataItems.getGiftTypeId(), 
                                                                                               dataItems.getGiftTypeId());
                    //System.out.println("rowNumber" + counter + " is " + dataItems.getGiftTypeId());
                  }
                  }
                  catch (SQLException e) {
                      new com.mobinil.gvms.system.utility.PrintException().printException(e);
                  }
              


          }
        count++;

      }
    msgWarn = "Gift type deleted";
    // Do your thing with the MyData items in List selectedDataList.
    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().remove("GiftType_Bean");
    return "refreshGiftType"; // Navigation case.
  }

  public String newGiftType()
  {

    return "createGiftType";
  }

  public String editGiftType()
  {

    dataItem = (GiftTypeDTO) dataTable1.getRowData();    
    jsfUtils.removeFromSession("GiftTypeInfo");
    FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("GiftTypeInfo", 
                                                                               dataItem);
    


    return "editGiftType";
  }

  public void pageFirst()
  {
    dataTable1.setFirst(0);
    pageIndex = 0;
  }

  public void pagePrevious()
  {
    dataTable1.setFirst(dataTable1.getFirst() - dataTable1.getRows());
    pageIndex--;
  }

  public void pageNext()
  {
    dataTable1.setFirst(dataTable1.getFirst() + dataTable1.getRows());
    pageIndex++;
    //System.out.println("get rows " + dataTable1.getRows());
    //System.out.println("get row count " + dataTable1.getRowCount());
  }

  public void pageLast()
  {
    pageIndex = dataTable1.getRowCount();
    int count = dataTable1.getRowCount();
    int rows = dataTable1.getRows();
    dataTable1.setFirst(count - ((count % rows != 0)? count % rows: rows));
  }


  public void setForm1(HtmlForm form1)
  {
    this.form1 = form1;
  }

  public HtmlForm getForm1()
  {
    return form1;
  }

  public void setGiftTypeArray(ArrayList<GiftTypeDTO> GiftTypeArray)
  {
    this.GiftTypeArray = GiftTypeArray;
  }

  public ArrayList<GiftTypeDTO> getGiftTypeArray()
  {
    return GiftTypeArray;
  }

  public void setDataTable1(HtmlDataTable dataTable1)
  {
    this.dataTable1 = dataTable1;
  }

  public HtmlDataTable getDataTable1()
  {
    return dataTable1;
  }

  public void setMsgWarn(String msgWarn)
  {
    this.msgWarn = msgWarn;
  }

  public String getMsgWarn()
  {
    return msgWarn;
  }

  public void setRowCount(Integer rowCount)
  {
    this.rowCount = rowCount;
  }

  public Integer getRowCount()
  {
    return rowCount;
  }

  public void setSortField(String sortField)
  {
    this.sortField = sortField;
  }

  public String getSortField()
  {
    return sortField;
  }

  public void setSortAscending(boolean sortAscending)
  {
    this.sortAscending = sortAscending;
  }

  public boolean isSortAscending()
  {
    return sortAscending;
  }
}

web/Admin/Gift/GiftType/CreateGiftType.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<%@page errorPage="/error.jsp"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://myfaces.apache.org/tomahawk" prefix="t"%>
<f:view>
 <html>
  <head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
   <title>CreateGiftType</title>
   <link rel="stylesheet" type="text/css" href="../../../css/Login.css"/> 
   
   
  </head>
  <body>
    <center>
    
    
    
    

<table id="Table_01" width="800" height="601" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td bgcolor="#988f86">
			<img src="../../../images/Welcome/new/internal-english_01.gif" width="84" height="84" alt=""></td>
		<td colspan="3" bgcolor="#988f86" align="left" width="512" height="84">
			<label style="color: white;font-family: Arial;font-weight: bold;font-size: 30px;"> New Gift Type</label></td>
		<td colspan="2" bgcolor="#988f86">
			<img src="../../../images/Welcome/new/internal-english_03.gif" width="204" height="84" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" valign="top" width="222" height="414">
			
			   <table width="100%">
          
         
         <tr>
            <td >
         <%@ include file="/Admin/AdminLefMenu.jsp"%>
              
            </td>
          </tr>
          
        </table>
			</td>
		<td colspan="3" align="center" valign="top"  width="578" height="414">
		
		
		<!-- cut from here -->
	 <h:form binding="#{CreateGiftType_Bean.form1}" id="form1">
        <table width="68%" height="75">
         <tr>
          <td width="16%" align="left" >Name*</td>
          <td width="84%" align="left">
           <h:inputText style="width:50%" binding="#{CreateGiftType_Bean.giftTypeNameInput}"
                        id="giftTypeNameInput"/>          </td>
         </tr>
         <tr>
          <td width="16%" align="left">Description</td>
          <td width="84%" align="left">
           <h:inputTextarea style="width:50%" binding="#{CreateGiftType_Bean.giftTypeDesTexArea}"
                            id="giftTypeDesTexArea"/>          </td>
         </tr>
         <tr>
          <td width="16%" align="left">Status*</td>
          <td width="84%" align="left">
           <t:selectOneMenu style="width:50%" value="#{CreateGiftType_Bean.status}">
            <f:selectItem  itemLabel="--Select One--" itemValue="0"/>
            <f:selectItem itemLabel="ACTIVE" itemValue="1"/>
            <f:selectItem itemLabel="IN ACTIVE" itemValue="2"/>
           </t:selectOneMenu>             </td>
         </tr>
         <tr>
           <td align="left">&nbsp;</td>
           <td align="left">&nbsp;</td>
         </tr>
         <tr>
           <td align="left"><h:commandButton value="Add "
                          binding="#{CreateGiftType_Bean.addGT_cmd}"
                          id="addGT_cmd"
                          action="#{CreateGiftType_Bean.AddGiftType}"/></td>
           <td align="left"><h:commandButton value="Back"
                          action="#{CreateGiftType_Bean.back_Action}"
                          id="commandButton1"/></td>
         </tr>
        </table>
        <p>
         
          
         <h:outputLabel binding="#{CreateGiftType_Bean.msgWarn}" id="msgWarn"/>
          
         
        </p>
        </h:form>
        
       <!-- cut to here -->
		        </td>
        
</tr>
        
	
	<%@ include file="../../Adminfooter.jsp" %>
	<tr>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="84" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="51" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="87" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="374" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="197" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="7" height="1" alt=""></td>
	</tr>
</table>
     
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    </center>
   </body>
 </html>
</f:view>
<%-- oracle-jdev-comment:auto-binding-backing-bean-name:CreateGiftType_Bean--%>

web/Admin/Gift/GiftType/GiftType.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<%@page errorPage="/error.jsp"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<f:view>
 <html>
  <head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
   <title>GiftType</title>
   <link rel="stylesheet" type="text/css" href="../../../css/Login.css"/>
   <script type="text/javascript" src="../../../css/showReportss.js"></script>
      <script type="text/javascript" src="../../css/selectallcheckbox.js"></script>
   <style type="text/css">
      .yearRowStyle {
                 background-color: #A8D1E8;
                 color: green;
                 text-align: center;
                 font-weight: bold;
                 font-style:italic;
                }
            .weekRowStyle {
                 background-color: #D6EBFC;
                }
            .selectedDayCellStyle {
                background-color: #ECD5D2;
                }
      
      .row1 {
    background-color: #ddd;
        }
      .row2 {
    background-color: #bbb;
        }
      </style>
  
  </head>
  <body>
    <center>
    
    
    
    
    

<table id="Table_01" width="800" height="601" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td bgcolor="#988f86">
			<img src="../../../images/Welcome/new/internal-english_01.gif" width="84" height="84" alt=""></td>
		<td colspan="3" bgcolor="#988f86" align="left" width="512" height="84">
			<label style="color: white;font-family: Arial;font-weight: bold;font-size: 30px;"> Gift Type</label></td>
		<td colspan="2" bgcolor="#988f86">
			<img src="../../../images/Welcome/new/internal-english_03.gif" width="204" height="84" alt=""></td>
	</tr>
	<tr>
		<td colspan="3" valign="top" width="222" height="414">
			
			   <table width="100%">
          
         
         <tr>
            <td >
         <%@ include file="/Admin/AdminLefMenu.jsp"%>
              
            </td>
          </tr>
          
        </table>
			</td>
		<td colspan="3" align="center" valign="top"  width="578" height="414">
		
		
		<!-- cut from here -->
	<h:form id="giftTypeFormId">
        <h:dataTable width="100%" rowClasses="row1,row2"
                     value="#{GiftType_Bean.giftTypeArray}" var="Dtvar"
                     binding="#{GiftType_Bean.dataTable1}" id="dataTable1"
                     style="text-align:center; vertical-align:middle;"
                     border="1" rows="#{GiftType_Bean.rowCount}">
                     
         <!--oracle-jdev-comment:Faces.RI.DT.Class.Key:java.util.ArrayList<Admin.View.GiftTypeClass>-->
         <h:column>
         <f:facet name="header">
           <h:panelGroup>
            <h:selectBooleanCheckbox id="mainCheckBox" onclick="checkAll('giftTypeFormId:dataTable1',':list')"/>
            
           </h:panelGroup>
          </f:facet>
          <h:selectBooleanCheckbox id="list" value="#{Dtvar.selected}"/>
         </h:column>
         
         <h:column>
          <f:facet name="header">
           <h:commandLink  actionListener="#{GiftType_Bean.sortDataTable}">
           <f:attribute name="sortField" value="getGiftTypeName" />
           <h:outputText style="color:rgb(0,0,0); font-size:small;" value="Name"/>
           </h:commandLink>
          </f:facet>
          <h:outputText value="#{Dtvar.giftTypeName}"/>
         </h:column>
         <h:column>
          <f:facet name="header">
           <h:commandLink  actionListener="#{GiftType_Bean.sortDataTable}">
           <f:attribute name="sortField" value="getGiftTypeStatus" />
           <h:outputText style="color:rgb(0,0,0); font-size:small;" value="Status"/>
           </h:commandLink>
          </f:facet>
          <h:outputText value="#{Dtvar.giftTypeStatus}"/>
         </h:column>
         
         <h:column>
          <f:facet name="header">
           <h:outputText value="DESCRIPTION"/>
          </f:facet>
          <h:outputText value="#{Dtvar.giftTypeDescription}"/>
         </h:column>
         
         <h:column>
          <f:facet name="header">
           <h:outputText value="Edit"/>
          </f:facet>
          <h:commandButton value="Edit" action="#{GiftType_Bean.editGiftType}"/>
         </h:column>
         <f:facet name="footer">
          <h:panelGroup>
           <h:commandButton value="First" action="#{GiftType_Bean.pageFirst}"
                            disabled="#{GiftType_Bean.dataTable1.first == 0}"/>
           <h:commandButton value="Prev" action="#{GiftType_Bean.pagePrevious}"
                            disabled="#{GiftType_Bean.dataTable1.first == 0}"/>
           <h:commandButton value="Next" action="#{GiftType_Bean.pageNext}"
                            disabled="#{GiftType_Bean.dataTable1.first + GiftType_Bean.dataTable1.rows>= GiftType_Bean.dataTable1.rowCount}"/>
           <h:commandButton value="Last" action="#{GiftType_Bean.pageLast}"
                            disabled="#{GiftType_Bean.dataTable1.first + GiftType_Bean.dataTable1.rows>= GiftType_Bean.dataTable1.rowCount}"/>
          </h:panelGroup>
         </f:facet>
        </h:dataTable>
        <h:inputHidden value="#{GiftType_Bean.sortField}" />
        <h:inputHidden value="#{GiftType_Bean.sortAscending}" />
        <h:commandButton value="Create new GiftType" id="createGiftType"
                         action="#{GiftType_Bean.newGiftType}"/>
        <h:commandButton value="Remove Selected Gift Type"
                         action="#{GiftType_Bean.getSelectedItems}"/><br>
        <h:outputLabel value="#{GiftType_Bean.msgWarn}"/>
        </h:form>
        
       <!-- cut to here -->
		        </td>
        
</tr>
        
	
	<%@ include file="../../Adminfooter.jsp" %>
	<tr>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="84" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="51" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="87" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="374" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="197" height="1" alt=""></td>
		<td>
			<img src="../../../images/Welcome/new/spacer.gif" width="7" height="1" alt=""></td>
	</tr>
</table>
     
    
    
    
    </center>
   </body>
 </html>
</f:view>
<%-- oracle-jdev-comment:auto-binding-backing-bean-name:GiftType_Bean--%>